### ISSUE TITLE
White and Buggy

### ISSUE THREAD

**Issue by Alexxonder** [IsSuEat/open-livestreamer-firefox-addon#43]
My addon is white with white text and everything, so i can't see which quality what is, is this outdated?
http://www.mediafire.com/view/i07w7pq9sw98pj2/Screenshot%20%2856%29.png#

**Comment by julianrichen** [comment]
It's seems to be switching to the dark theme variant because it detected the current theme to have a dark background compared to the text, can you switch to another theme (preferably light) to confirm that?

The icon seems to have changed but not background color, I wonder if Mozilla changed the code used to detect that.

**Comment by julianrichen** [comment]
Finally found the time to look into this. If you had a link to that theme it would make it much easier to debug.

From what I can tell, themes that causes issue like this are generally poorly coded. They set light backgrounds then apply a dark image over it. The code we have checks for the background color as it can't test the background color of an image.

The best solution would be to have the automatic detection (like we do now) with a fallback option in about:addons with a dropdown like so:

Theme Detection
Use the light or dark theme or let Open in Livestreamer detect it automatically (results may vary).
`['Auto', 'Light', 'Dark']`

Users can force a mode if their theme does not work with the addon, I wish the Firefox SDK had an api for this -_-
