### ISSUE TITLE
Deprecation

### ISSUE THREAD

**Issue by ZatsuneNoMokou** [IsSuEat/open-livestreamer-firefox-addon#47]
```
const { Cc, Ci } = require("chrome");
```

You are using a deprecated api, launching livestreamer isn't possible with system/child_process?

**Comment by IsSuEat** [comment]
Sure is possible, I think as it is used in the plugin aswell. It was not available when the inital code was written. 
Thanks for pointing that out, I will look into this.

**Comment by ZatsuneNoMokou** [comment]
I tried with my own addon, but the command doesn't seems to be able to launch the player, I don't understand why, the livestreamer output seems normal. There's a special thing to do?

**Comment by julianrichen** [comment]
I remember trying to get system/child_process working initially but for whatever reason it refused to create a child process. It was refusing the arguments passed. It seems like it has been significantly worked on since I used it so maybe it was a bug before?
https://developer.mozilla.org/en-US/Add-ons/SDK/Low-Level_APIs/system_child_process

We currently use it to get the json string from livestreamer about the different quality levels on [lib/main.js#L218](https://github.com/IsSuEat/open-livestreamer-firefox-addon/blob/master/lib/main.js#L218) so clearly it works to a degree.

They don't say when they plan to deprecate but [they do say](https://developer.mozilla.org/en-US/Add-ons/SDK/Low-Level_APIs/chrome):
> If you use this API you can expect your add-on to get an extra security review by addons.mozilla.org.

That alone is worth the switch.

**Comment by julianrichen** [comment]
I think I sorta understand the issue. I changed `runLivestreamer ()` to the following and placed the require system process at the top of main.js
```
// Run Livestreamer
function runLivestreamer(args) {
    var path,
        file;
    // Notify
    panel.width = 250;
    panel.height = 97;
    panel.port.emit("status", locale("status_lauching"));
    panel.port.emit("loading", true);
    // Get livestreamer path
    path = getLivestreamerPath();
    // Launch livestreamer
    var live = process.spawn(path, args);
    
    live.stdout.on('data', function (data) {
      console.log('stdout: ' + data);
    });

    live.stderr.on('data', function (data) {
      console.log('stderr: ' + data);
    });

    live.on('close', function (code) {
      console.log('child process exited with code ' + code);
    });
}
```

The console returned the following:
```
onsole.log: open-livestreamer: stdout: [cli][info] Found matching plugin twitch for URL http://www.twitch.tv/esl_csgo

console.log: open-livestreamer: stdout: [cli][info] Available streams: audio, high, low, medium, mobile (worst), source (best)
[cli][info] Opening stream: source (hls)

console.log: open-livestreamer: stdout: error: The default player (VLC) does not seem to be installed. You must specify the path to a player executable with --player.
```

I think the issue is because it creates a child process. This process is then isolated so it can't scan the system for vlc? We need to provide the path with `--player`.

However, this won't work:
```
args.push('--player /usr/bin/vlc');
var live = process.spawn(path, args);
```

And this sorta works:
```
args.push('--player','/usr/bin/vlc');
var live = process.spawn(path, args);
```

but returns:
```
console.log: open-livestreamer: stdout: [cli][info] Found matching plugin twitch for URL http://www.twitch.tv/elvinemod

console.log: open-livestreamer: stdout: [cli][info] Available streams: audio, high, low, medium, mobile (worst), source (best)
[cli][info] Opening stream: source (hls)

console.log: open-livestreamer: stdout: [cli][info] Starting player: /usr/bin/vlc

console.log: open-livestreamer: stdout: [cli][info] Player closed

console.log: open-livestreamer: stdout: [cli][info] Stream ended

console.log: open-livestreamer: child process exited with code 0
```

It's temporarily works then right before it launches it stops :/

**Comment by ZatsuneNoMokou** [comment]
I know :/ it's because the version that Firefox API use of child process break completely the env part from NodeJS

**Comment by ZatsuneNoMokou** [comment]
That written [here](https://developer.mozilla.org/en-US/Add-ons/SDK/Low-Level_APIs/system_child_process) 

> The SDK versions don't: so when you specify a command you must pass in a complete path to the command or use the env option to set up the child process environment.

**Comment by ZatsuneNoMokou** [comment]
For information my addon is this one https://gitlab.com/ZatsuneNoMokou/live_notifier

**Comment by IsSuEat** [comment]
I tried it aswell yesterday, but wasnt able to launch any player either. Appending -v to livestreamer prints out any player errors that happen. This shows some crashed somewhere in firefox, but I couldn't really figure out a way around it.

It seems that spawn() will only spawn one child process, and won't allow that child to fork()
(I think this somehow makes sense in the light of security)

So currently I think @julianrichen's idea with spawning a shell and executing livestreamer from there seems the best.

**Comment by ZatsuneNoMokou** [comment]
If you find how to make it work well, I'm interested

**Comment by julianrichen** [comment]
Some more testing.

Adding `{shell: true}` does nothing:
```js
args.push('--player=/usr/bin/vlc');
var live = process.spawn(path, args, {shell: true});
```

Try to launch a shell and passing livestreamer as an argument does not work
```js
args.unshift(path); // /usr/bin/livestreamer
args.push('--player=/usr/bin/vlc');
var live = process.spawn("/bin/sh", args, {detached: true, shell: true});
```

Detaching the process does not work:
```js
args.push('--player=/usr/bin/vlc');
var live = process.spawn(path, args, {detached: true});
```

Why? Because it's not supported. Wooohooo!
```
console.warn: open-livestreamer: `detached` option is not yet supported for `child_process`
```

What about keeping the connection open?
```js
var live = process.spawn(path, args, {detached: true});
live.unref()
```

Nope `.unref()` is not supported.

I'm out of ideas. I guess we could asking on the forums:
https://discourse.mozilla-community.org/c/add-ons

**Comment by ZatsuneNoMokou** [comment]
Well, that api is written as "Experimental" on Mozilla doc, so, it's not surprising

**Comment by julianrichen** [comment]
True but the fact that they are already starting to deprecate one method while not having the other method ready is annoying. I love Mozilla and all that they stand for but they have done this kind of stuff in the past with extension signing -_-

**Comment by ZatsuneNoMokou** [comment]
True, I'm using a self-host version for my dev version, because using console.*() shouldn't be used "in production" build...

**Comment by IsSuEat** [comment]
Okay, I'm at the same conclusion as @julianrichen . Tried all that came to mind, but no success yet. I'd say we wait for this API to mature before actually bothering with it again. 

I looked through the open defects on their bugzilla but couldn't really find a similar issue. 
I'm trying to get some actual details out of firefox where it fails and will eventually open a bugreport

**Comment by ZatsuneNoMokou** [comment]
I was thinking that it could be for security but dunno, maybe it's just a bug
