### ISSUE TITLE
Youtube?

### ISSUE THREAD

**Issue by 21246685** [IsSuEat/open-livestreamer-firefox-addon#48]
Youtube stopped working recently.

It opens up but stream is just frozen and not playing

**Comment by julianrichen** [comment]
I just check and I'm seeing this as well, but only on YouTube LIVE streams. Regular videos work.

This addon is dependent on [chrippa/livestreamer](https://github.com/chrippa/livestreamer) and there has not been an update since May 2015.

This [bug report](https://github.com/chrippa/livestreamer/issues/1254) seems to be the same issue you are having. We can't fix anything on the plugin side.

If livestreamer does not get updated again and more stuff breaks it might be worth looking into #15 as a necessary feature.
