### ISSUE TITLE
Inadequate Instructions to do YOUR Job For You

### ISSUE THREAD

**Issue by SiberYid** [IsSuEat/open-livestreamer-firefox-addon#57]
As is SO often the case, a complete lack of clear + accurate instructions, for what is hardly the most straightforward add-on. Options in Firefox Add-ons Manager opens up a page of mysteries, the .html link doesn't behave in the usual manner (right click, no 'open in new tab' option), disable? remove? about? How do I get this list of supported sites?? The .io link, ......needs to be installed? I have installed it, haven't I? Why can't I copy + paste this link? Then, "Path to Livestreamer", which looks as though something needs to be added, I don't know what? And there's no explanation, so what do I do? 
Waste my time scratching about, slowly figuring stuff out, is usually the answer + all because the "Tech World" is failing so abysmally to make stuff that doesn't demand so much from the user, + doesn't provide instruction on how to carry out those demands. Do you have to be some sort of technician to utilise all this technology? In a way, yes, you do, because it seems to me that the idea of the User being the Master, + the PC being a servant is far from reality, vice versa is often more like it.
If you can't design software that doesn't depend on user servitude, then at least try to take into account the user may not be a 'technician' + provide adequate instruction, after all, the user is doing what surely is YOUR job.

**Comment by julianrichen** [comment]
On the addon page & GitHub it says:
> Launch **livestreamer** from twitch.tv, hitbox.tv or youtube

and:
> This Addon opens sites like twitch.tv, hitbox.tv, YouTube, etc.. with [**Livestreamer**](http://livestreamer.io/), stream in your favourite mediaplayer. Browse to a stream on one of the supported sites an click the "Open with Livestreamer" button. The settings can be edited via the Firefox Addon Manager.

And most importantly this....
> **Livestreamer needs to be installed**
> http://docs.livestreamer.io

This add-on clearly launches **Livestreamer**, a streaming program: http://livestreamer.io
You need to install **Livestreamer**: http://docs.livestreamer.io/install.html
Which offers streaming for the following sites: http://docs.livestreamer.io/plugin_matrix.html
You also need a video player like VLC: http://www.videolan.org
If you have additional questions a wiki exists: https://github.com/IsSuEat/open-livestreamer-firefox-addon/wiki
And livestreamer has a guide for each platform: http://docs.livestreamer.io/install.html

The "Open livestreamer" add-on should auto-detect Livestreamer if it's installed in the default location, if not you may need to do some custom config. Hence check the wiki about doing that. Your disaster of a post seems to indicate you understood some of that.... sorta... Near the end you got philosophical about the PC and the master/servant thing so.... idk. It's more of a rant if anything.

I feel like I should point out the following:
This add-on is free software and created by people on their free time for other Firefox users, they owe you absolutely nothing. Treating a free software project as a "job", which provides the developers no financial gain and are normally created simply because they like giving back to the community, is insulting to those behind the project.

Understanding basic instructions and using problem solving skills is YOUR JOB. When you have a question because you're lost, I would recommend that you post with a little respect instead of bashing those who provide free services and programs. You also failed to create a valid issue. Without providing any useful information like the OS, Firefox, add-on, and livestreamer version, etc... people can't really help you.

You seem to be new to GitHub and free software? Hopefully you can learn from this and provide meaningful contributions back to the community.

Regards

**Comment by SiberYid** [comment]
Julian,     please accept my sincere apologies for my ignorance + wildly inappropriate complaint, it never crossed my tiny, limited mind that you aren't M'soft, or some other faceless giant, but are in actual fact individuals providing software, skills, + such like, free of charge. I accept every word you said + have been put firmly in my place, you can be sure of that. My pitiful ineptitude + general incompetence gets the better of me + I try to blame someone/thing, whatever I can think of at the time, for my hopeless failures.
 I thank you for pointing out some truths I was so clearly in need of knowing, ignorance is no excuse, I know that. I'm also aware that your reply showed me more respect than I deserved + the restraint you showed by remaining civil was admirable, + again more than I was due. As you said, no one in your organization owes me the merest of not one single thing. I, of course, owe a sincere apology for the disrespect I showed, + for the ill-informed + undeserved slants you so rightly brought to my attention just how wide of the mark + based on pure ignorance my comments were, which I assure you I truly am sorry for making them. What you provide free of charge I'll take care in the future to show the respect your efforts undeniably deserve.
Sincerely,
   Si Hammer
