### ISSUE TITLE
Transition to streamlink 

### ISSUE THREAD

**Issue by IsSuEat** [IsSuEat/open-livestreamer-firefox-addon#60]
As livestreamer seems to be deprecated we should think about moving to streamlink [0], because 
the majority of users seem to use twitch and this needs a workaround / is broken.

In practice this isn't hard, just change the path to the executable; but if we just change it, it might affect users, that are relying on the default paths and livestreamer.

Should we just add the default paths for streamlink aswell and check if any is valid?
Or display a deprecation warning when livestreamer is started?

What's your take on this,  @julianrichen 

[0] http://streamlink.github.io/

**Comment by Shaaah** [comment]
Well, I was going to create an issue on the same exact thing!

It's still possible to use streamlink with this addon, there is an option in to change the executable path, and putting the streamlink one there works like a charm.

**Comment by julianrichen** [comment]
@IsSuEat The approach I would take is to make livestreamer, steamlink & youtube-dl act as plugins for the add-on so they are easy drop-in/out replacement when one fails.

We should definitely look into WebExtentions and #53 because it implements Native Messaging and allows for easier and safer client side binary execution (or Python in our case). Plus the old method we are using atm will be dropped eventually. ~~I remember we were on hold because WebExtentions were not finalized on Mozilla but maybe they are now?~~

`runtime.connectNative()` will have basic support in Firefox 50.0:
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/Runtime/connectNative

**Comment by hodor22** [comment]
Like Shaaah,
I just added C:\Program Files (x86)\Streamlink\bin\streamlink.exe into the path to livestreamer window of the addon and its working again! I love the addon! thx
